### ISSUE TITLE
Exception: "[WinError 32] Processen kan ikke få adgang til filen, da den bruges af en anden proces: 'carrots'"

### ISSUE THREAD

**Issue by MegetSkuffet** [Duckapple/Kat#109]
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 813, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] Processen kan ikke få adgang til filen, da den bruges af en anden proces: 'carrots' -> '.solved/carrots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\malte\Documents\kattis\Kat\kattis.py", line 41, in main
    execCommand[command](data)
  File "C:\Users\malte\Documents\kattis\Kat\commands\submit.py", line 85, in submitCommand
    archive(problemName, ".solved/")
  File "C:\Users\malte\Documents\kattis\Kat\commands\archive.py", line 30, in archive
    shutil.move(problemName, folder + problemName)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 831, in move
    rmtree(src)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 747, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 621, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 619, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] Processen kan ikke få adgang til filen, da den bruges af en anden proces: 'carrots'

```

**Comment by Duckapple** [comment]
The file is used by another process, and cannot be moved. Are you running the debugger in the background when this error appears?
