### ISSUE TITLE
Exception: "can only concatenate str (not "NoneType") to str"

### ISSUE THREAD

**Issue by Jakobis** [Duckapple/Kat#68]
```
Traceback (most recent call last):
  File "C:\Users\Clipsterman\PycharmProjects\Kat\kattis.py", line 40, in main
    execCommand[command](data)
  File "C:\Users\Clipsterman\PycharmProjects\Kat\commands\submit.py", line 81, in submitCommand
    losesound()
  File "C:\Users\Clipsterman\PycharmProjects\Kat\helpers\sound.py", line 12, in losesound
    playsound(playsound(random.choice(glob.glob(prefix + "/lose/*.mp3"))))
  File "C:\Users\Clipsterman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by Duckapple** [comment]
Fixed by d1db290
