### ISSUE TITLE
Exception: "'utf-8' codec can't decode byte 0xe5 in position 23: invalid continuation byte"

### ISSUE THREAD

**Issue by Navarot** [Duckapple/Kat#76]
Can't handle special characters in `print()` statement, throws the above exception (I tried with the Danish 'å' letter.)

In addition, at submission, because of the issue, it replaces the special characters with others, producing a 'Wrong answer' result.

```
Traceback (most recent call last):
  File "C:\Users\path\to\Kat-master\kattis.py", line 40, in main
    execCommand[command](data)
  File "C:\Users\path\to\Kat-master\commands\test.py", line 57, in testCommand
    result, time = runSingleTest(command, directory, inF, ansF)
  File "C:\Users\path\to\Kat-master\commands\test.py", line 107, in runSingleTest
    subprocess.run(command, stdout=subprocess.PIPE, input=inp, cwd=directory)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 23: invalid continuation byte

```

**Comment by Duckapple** [comment]
Can you check the encoding of the source file? (e.g. by checking your status bar at the bottom in VS Code)

**Comment by Navarot** [comment]
It's UTF-8
