### ISSUE TITLE
Submit crashes when including slashes

### ISSUE THREAD

**Issue by Jakobis** [Duckapple/Kat#78]
Most commands, like archive and test, work fine if you tab to complete them, even though the command ends up looking like .\simplecronspec\, but submit crashes. 

```
Traceback (most recent call last):
  File "C:\Users\Clipsterman\PycharmProjects\Kat\kattis.py", line 40, in main
    execCommand[command](data)
  File "C:\Users\Clipsterman\PycharmProjects\Kat\commands\submit.py", line 66, in submitCommand
    "📬 Submission Successful (url " + getConfigUrl("submissionsurl", "submissions") + "/" + id + ")"
TypeError: can only concatenate str (not "int") to str

```

**Comment by Duckapple** [comment]
Closed by #79
