### ISSUE TITLE
Play sound crashes on windows, not sure why :)

### ISSUE THREAD

**Issue by MikkelNilsson** [Duckapple/Kat#89]
```
Traceback (most recent call last):
  File "D:\.Projekter\Kat\kattis.py", line 41, in main
    execCommand[command](data)
  File "D:\.Projekter\Kat\commands\submit.py", line 81, in submitCommand
    winsound()
  File "D:\.Projekter\Kat\helpers\sound.py", line 8, in winsound
    playsound(random.choice(glob.glob(prefix + "/win/*.mp3")))
  File "C:\Users\mikke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\mikke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException: 
    Error 305 for command:
        open "D:\.Projekter\Kat\helpers/../resources//win\win.mp3"
    Der kan ikke angives ekstra tegn efter en streng, som er omgivet af anførelsestegn.

```

**Comment by Duckapple** [comment]
I have pushed what I think is a fix to master -- could you check whether it works?

**Comment by MikkelNilsson** [comment]
Hey, just tested it out. It works now 👍
